### PR TITLE
Support for GHC 8.4.1

### PR DESCRIPTION
**Pull request by varosi**
Tested on Windows 10 x64. And a try to add Travis build.

### CODE REVIEW

**Comment by DanBurton** [comment]
Bump. Would really appreciate this being merged and released. ❤️

**Comment by DanBurton** [comment]
I have tested this on my local machine like so:

```bash
stack upgrade --git --git-branch stable
git clone https://github.com/varosi/haskell-src-meta
cd haskell-src-meta/
echo 'resolver: nightly-2018-03-14' > stack.yaml
stack test
```

I have also verified that this should be a safe revision to make on the existing haskell-src-meta like so:

```bash
# same stack upgraded from git
stack unpack haskell-src-meta-0.8.0.2 && cd haskell-src-meta-0.8.0.2
echo 'resolver: nightly-2018-03-14' > stack.yaml
edit haskell-src-meta.cabal # relax base and template-haskell constraints, as in this PR
stack test
```

A prompt release and/or revision would be much appreciated, as I'd love to get this into the next Stackage nightly!

**Comment by mgsloan** [comment]
Pinging @bmillwood @mainland .  Also if you like, I wouldn't mind becoming a comaintainer.  Even though I don't have any commits to this package, I'm quite familiar with both HSE and TH.

**Comment by hvr** [comment]
Can anybody confirm that the changes in TH 2.13 don't affect the correctness of `haskell-src-meta
` beyond having merely blindly running the test-suite?

**Comment by mgsloan** [comment]
If the changelog for TH is accurate, then I don't think the correctness of `haskell-src-meta` has changed any.  The only thing potentially changed is the addition of overloaded labels - https://hackage.haskell.org/package/template-haskell-2.13.0.0/changelog - but that's also mentioned in 2.12 - seems like this release might have just added `labelE`.

Note that `haskell-src-meta` is missing quite a few cases in its translation anyway (see uses of `todo`, and try turning on `-Wall`).  The package could use some improvement - it's been roughly in that state for many years, though.  I think I'd rather put development time into adding `parseExp :: String -> Exp` and similar function sto TH, or something along those lines.

**Comment by bergmark** [comment]
Sounds reasonable @mgsloan,

I've filed a revision for this: https://hackage.haskell.org/package/haskell-src-meta-0.8.0.2/revisions/

Please let me know if there are any issues.

**Comment by DanBurton** [comment]
The packages downstream of this that I am aware of are also happily building and passing their test suites because of this revision. Nothing broken because of it that I can see so far. Thanks @bergmark.

**Comment by JonasDuregard** [comment]
Since the cabal file on hackage already had the relaxed version bounds, and I have been using haskell-src-meta successfully on GHC 8.4.3, I updated the version bounds in a9a75a880c2bb15ad95686e4af96993e67b63695.

**Pull request closed without merging**
