### PR TITLE
Support GHC 8.6

### PR DESCRIPTION
**Pull request by ckoparkar**

### CODE REVIEW

**Comment by ckoparkar** [comment]
@bmillwood ping :)

**Comment by ckoparkar** [comment]
@JonasDuregard I was looking at Hackage and saw that you're helping Ben with some of the maintenance work. Could you please take a look at this PR ?

**Comment by peti** [comment]
Ping?

**Comment by ckoparkar** [comment]
Thanks a lot @JonasDuregard!

**Pull request merged**
