### PR TITLE
Support haskell-src-exts 1.21.

### LINKED ISSUE #85: Fails to build with haskell-src-exts 1.21.0.
The commit https://github.com/haskell-suite/haskell-src-exts/commit/cc3188726c3d4ebd30a27d036c812ddd47d0d9fb replaced the `data Kind l` declaration, making instead `Kind` a synonym for `Type`.  As a result, `Language/Haskell/Meta/Syntax/Translate.hs` fails to compile with the current `haskell-src-exts`, starting at this instance declaration: https://github.com/bmillwood/haskell-src-meta/blob/8bfa70a501ed048298ecf992f613b3237631c98a/src/Language/Haskell/Meta/Syntax/Translate.hs#L317

This stuff is a bit over my head, so I'm not sure how to fix it.  Maybe this instance is no longer needed at all?

### PR DESCRIPTION
**Pull request by galenhuntington**
I believe this resolves #85.

### CODE REVIEW

**Comment by alexeyzab** [comment]
Would be nice to get this merged in since it's the last package from this issue: https://github.com/commercialhaskell/stackage/issues/4214

**Comment by DanBurton** [comment]
Pinging @bmillwood, @JonasDuregard, and @mainland, who are able to merge & upload.

Or, if you'd like to grant me commit & upload rights on github & hackage, I'd be happy to do it for you.

**Comment by DanBurton** [comment]
I've taken over the package and uploaded haskell-src-exts-0.8.1, which includes this change.

See: https://github.com/DanBurton/haskell-src-meta/pull/1

**Comment by bmillwood** [comment]
Looks like Dan's covered this in his fork of this repo. I added him as a contributor just in case.

**Pull request closed without merging**
